ucsb-cs56-w20/open-lab-scheduler

- .github/workflows/maven.yml
In this PR we add the needed files for GitHub Actions as our CI system.
> pc/team - setup github actions

- pom.xml
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/RoomAvailability.java
- src/main/resources/data.sql
- src/main/resources/templates/index.html
In this PR, we add quarter to room availability
We also fixed some duplicate and commented out code in pom.xml
> Pc add quarter to room availability

- .gitignore
- README.md
- env.sh
- heroku.json.SAMPLE
- localhost.json.SAMPLE
- pom.xml
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/Application.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/advice/AuthControllerAdvice.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/ApplicationController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/GoogleMembershipService.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/MembershipService.java
- src/main/resources/application.properties
- src/main/resources/templates/bootstrap/bootstrap_footer.html
- src/main/resources/templates/bootstrap/bootstrap_head.html
- src/main/resources/templates/bootstrap/bootstrap_nav_header.html
- src/main/resources/templates/bootstrap/bootstrap_scripts.html
- src/main/resources/templates/bootstrap/title.html
- src/main/resources/templates/index.html
- src/main/resources/templates/login.html
- src/test/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/HomePageTest.java
yr/pc/rx - In this pr, we added google OAuth, Bootstrap nav bar and login/logout functionality.
> Add Google OAuth

- heroku.json.SAMPLE
- setHerokuEnv.py
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/GoogleMembershipService.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/MembershipService.java
In this PR we fix a bug where the GoogleMembershipService was not correctly
detecting admin status because of a incorrect ordering of conditions.
We also added the necessary support for deployment on Heroku
> pc/yr/rx - fix admin status bug and prepare for Heroku

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/AdminController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/Admin.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/AdminRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/ValidEmailService.java
- src/main/resources/templates/admin/create.html
- src/main/resources/templates/admin/form.html
- src/main/resources/templates/bootstrap/bootstrap_nav_header.html
In this pull request, we added a table for admins.
We implemented create, read, ~update~, and delete methods for it.
> Add admin table and basic CRD

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/CourseOfferingController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/CourseOffering.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/CourseOfferingRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/CSVToCourseOfferingServiceImpl.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/CSVToObjectService.java
- src/main/resources/templates/bootstrap/bootstrap_nav_header.html
- src/main/resources/templates/courseOffering.html
As the CSV to xxx features are all similar except the entity's definition, we created a generic CSVToObjectService Interface, so that all CSV implementation could extend this interface. 
Note: To use each implementation in controllers, you need to import the xxxServiceImpl instead of xxxService.
> Pw course offering table with csv

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorAssignmentController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TutorAssignment.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/CourseOfferingRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TutorAssignmentRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TutorRepository.java
- src/main/resources/data.sql
- src/main/resources/templates/bootstrap/bootstrap_nav_header.html
- src/main/resources/templates/bootstrap/bootstrap_scripts.html
- src/main/resources/templates/tutorAssignment.html
- src/main/resources/templates/tutorAssignment/manage.html
This PR adds an admin page for listing and modifying tutor assignments with a minimal UI.
> Implement tutor assignment CRUD operations

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorAssignmentController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TutorAssignment.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TutorAssignmentRepository.java
In this PR, we set up the proper `ManyToOne` relationship between `TutorAssignment` and the tables that have foreign keys in this table.
> pc/bt - make many to one relationship for TutorAssignment

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/Room.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/RoomAvailability.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TimeSlot.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TimeSlotAssignment.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TutorAssignment.java
- src/main/resources/application.properties
This pull requests modifies the current entity structure by having the entities to store entities as a field rather than the entity id.
> Tk csv upload

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorAssignmentController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/Tutor.java
- src/main/resources/application.properties
- src/main/resources/data.sql
- src/main/resources/templates/tutors/tutors.html
In this PR, I added a way for admins to see and modify which tutors are active. I added the boolean field 'isActive' to Tutor.java, and updated the tutors and tutor assignment pages to include the new field. On the tutors page, I added a column to represent whether each tutor is active, with a checkbox that the admin can use to update a tutor's active/inactive status. Changes that are made to these checkboxes are saved even after the page is reloaded. When new tutors are added using the CSV form, they are set to active by default. On the tutor assignments page, only the active tutors will show up when the admin tries to assign tutors to a class.
> t-5pm-d tutor isActive

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorAssignmentController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/Room.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/RoomAvailability.java
In this PR, I removed the wildcard imports in controllers/TutorAssignmentController.java, controllers/TutorController.java, entities/Room.java, and entities/RoomAvailability.java.
> t-5pm-d remove wildcard imports

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TimeSlotAssignment.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TimeSlotAssignmentRepository.java
As advised by Conrad, I added CourseOffering to TimeSlotAssignment. I then created TimeSlotAssignmentRepository and added a method to search by Course and Tutor to that interface.
> T-5pm-C Added search by Course and Tutor to TimeSlotAssignmentRepo

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/advice/AuthControllerAdvice.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/RoomAvailabilityController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorSignUpController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/RoomAvailability.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TimeSlot.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/RoomAvailabilityRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TimeSlotAssignmentRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TimeSlotRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TutorAssignmentRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TutorRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/GoogleMembershipService.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/MembershipService.java
- src/main/resources/templates/bootstrap/bootstrap_nav_header.html
- src/main/resources/templates/tutorSignUp/timeSlotAssignment.html
- src/main/resources/templates/tutorSignUp/tutorSignUp.html
sz - implemented sign up form and crud for TimeSlotAssignment table so that tutors can assign themselves to open lab hours
> Sign up form

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/CourseOfferingController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/RoomAvailabilityController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorController.java
- src/main/resources/templates/error.html
As a user, I can see a concise, well-designed and understandable error page for the server error that includes the information of the time, status, error and message of the error so that I won't see the unclear, default Whitelabel Error Page anymore.
> T 6pm d custom error page

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/InstructorMenuController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/CSVToObjectServiceImpl.java
- src/main/resources/application.properties
- src/main/resources/data.sql
- src/main/resources/templates/instructorMenu/getTutors.html
- src/main/resources/templates/instructorMenu/instructorMenu.html
add links to tutor of that course
> T 6pm c links to tutors

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/RoomAvailabilityController.java
- src/main/resources/templates/roomAvailability/edit.html
In this PR:
- Implemented a drop down menu for the 7 days of the week when creating/editing a RoomAvailability object
> t-5pm-c Drop Down Menu for Days in RoomAvailability

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/RoomAvailabilityController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/RoomAvailability.java
- src/main/resources/application.properties
- src/main/resources/templates/roomAvailability/edit.html
- src/main/resources/templates/roomAvailability/roomAvailability.html
In this PR:
- Added checks for valid time inputs when creating/editing a RoomAvailability
- Added error modals for invalid time inputs
- Added app.timeSlotDefaultDuration property in application.properties
- Added instructions for valid time inputs when creating/editing a RoomAvailability
> t-5pm-c Time Slot Instructions & Error Messages

- src/main/resources/templates/roomAvailability/edit.html
- src/main/resources/templates/roomAvailability/roomAvailability.html
In this PR:
- Used FontAwesome icons to replace edit and delete buttons in RoomAvailability
- Applied Bootstrap styles to create and save buttons in RoomAvailability
- Changed the edit.html page from a table of inputs to an actual form when creating/editing a RoomAvailability object
> t-5pm-c Revamped RoomAvailability UI

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/InstructorMenuController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/CourseOffering.java
- src/main/resources/data.sql
- src/main/resources/templates/bootstrap/bootstrap_head.html
- src/main/resources/templates/bootstrap/bootstrap_scripts.html
- src/main/resources/templates/instructorMenu/instructorMenu.html
As an instructor I can view all my courses by quarter and use the search bar to find my classes more easily,so that I improve efficiency and readability
> T 6pm c default sort course display

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/QuarterController.java
- src/main/resources/templates/bootstrap/bootstrap_nav_header.html
- src/main/resources/templates/quarter/courseLeads.html
- src/main/resources/templates/quarter/quarter.html
- src/main/resources/templates/tutorAssignment/manage.html
As an Admin, I can go to the Quarter interface and see all quarters from our sql data.
While on the quarter interface, I can select "Course Leads" next to my desired quarter and be redirected to the CourseLeads interface which displays a table with all courses and designated course leads that quarter. 
If a course is assigned no course leads, the message "no course leads" is displayed for that course.
Also, small formatting change to src/main/resources/templates/tutorAssignment/manage.html. I added buffer space between the header and table.
> PR: T 5pm d aw course leads

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/advice/AuthControllerAdvice.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/AdminController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/Admin.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/create.html
I removed the delete button next to the names of permanent admins
> T 6pm d delete button

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorProfileController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/TutorSignUpController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/TimeSlotAssignment.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TimeSlotAssignmentRepository.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/repositories/TutorAssignmentRepository.java
- src/main/resources/templates/bootstrap/bootstrap_nav_header.html
- src/main/resources/templates/tutorProfile/allAssignedCourses.html
- src/main/resources/templates/tutorProfile/allCourses.html
- src/main/resources/templates/tutorProfile/currentCourses.html
- src/main/resources/templates/tutorSignUp/timeSlotAssignment.html
sz - implemented tutor profile to see tutor's current assigned courses and old courses
> W 7pm c list open lab hours

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/CourseOfferingController.java
- src/main/resources/templates/courseOffering/courseOffering.html
- src/main/resources/templates/courseOffering/create.html
- src/main/resources/templates/courseOffering/form.html
Created new functionality to be able to create new courses in the course offering section. Admin are now able to create new courses that will show up in the course offering table using course Id, quarter, professor name and professor email.
> T 7pm b create courses

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/CourseOfferingController.java
- src/main/resources/templates/courseOffering/courseOffering.html
- src/main/resources/templates/courseOffering/update.html
update feature working. As an instructor(admin) I can update courses that already exist on the course offering table, requirements for creating new courses apply to these update.
> T 7pm b update course

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/RoomAvailabilityController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/services/RoomAvailabilityDownloadCSV.java
- src/main/resources/application.properties
- src/main/resources/templates/roomAvailability/roomAvailability.html
- src/main/resources/templates/tutorSignUp/tutorSignUp.html
As an Admin I can download a csv of the room availabilities so that I can save the information locally in a conventional format.
> T 6pm c room availability csv download

- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/controllers/CourseOfferingController.java
- src/main/java/edu/ucsb/cs56/ucsb_open_lab_scheduler/entities/CourseOffering.java
- src/main/resources/data.sql
- src/main/resources/templates/courseOffering/confirmDelete.html
- src/main/resources/templates/courseOffering/courseOffering.html
- src/main/resources/templates/courseOffering/form.html
implemented slots for TAs, LAs and 190J students for admin to manipulate.
> T 7pm b slots for t as
